EfcoreLayout/Models/UploadedDocument.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace EfcoreLayout.Models
{
    public partial class UploadedDocument
    {
        [Display(Name = "Document ID")]
        public int DocumentId { get; set; }

        [Required(ErrorMessage = "Please Upload Pan Card ")]
        [Display(Name = "Pan Card")]
        public string PanCard { get; set; }

        [Required(ErrorMessage = "Please Upload Aadhar Card")]
        [Display(Name = "Aadhar Card")]
        public string AadharCard { get; set; }

        [Required(ErrorMessage = "Please Upload Salary Slip")]
        [Display(Name = "Salary Slip")]
        public string SalarySlip { get; set; }

        [Required(ErrorMessage = "Please Upload LOA ")]
        [Display(Name = "Letter Of Approval")]
        public string Loa { get; set; }

        [Required(ErrorMessage = "Please Upload NOC ")]
        [Display(Name = "No Objection Certificate")]
        public string Noc { get; set; }

        [Required(ErrorMessage = "Please Upload Agreement")]
        [Display(Name = "Agreement")]
        public string Agreement { get; set; }

        [Display(Name = "Document verified Status")]
        public string DocumentverifiedStatus { get; set; }

        [Display(Name = "Application ID")]
        public int? ApplicationId { get; set; }

        [Display(Name = "Loan Approval Status")]
        public string LoanApprovalStatus { get; set; }

        [Display(Name = "Application ID")]
        public virtual UserDetail Application { get; set; }
    }
}

EfcoreLayout/Controllers/UploadedDocumentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EfcoreLayout.Models;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace EfcoreLayout.Controllers
{
    public class UploadedDocumentsController : Controller
    {
        private readonly HomeLoanContext _context;

        public UploadedDocumentsController(HomeLoanContext context)
        {
            _context = context;
        }

        // GET: UploadedDocuments
        public async Task<IActionResult> Index()
        {
            var uid = (from d in _context.UploadedDocuments orderby d.DocumentId descending select d.DocumentId).FirstOrDefault();
            var appdoc = (from d in _context.IncomeDetails orderby d.ApplicationId descending select d.ApplicationId).FirstOrDefault();
            var appid = (from e in _context.UserDetails orderby e.ApplicationId descending select e.ApplicationId).FirstOrDefault();

            if (appdoc != appid)
            {
                return RedirectToAction("create", "uploadeddocuments");
            }
            return RedirectToAction("Details", "uploadeddocuments", new { id = uid });
        }

        // GET: UploadedDocuments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var uploadedDocument = await _context.UploadedDocuments
                .Include(u => u.Application)
                .FirstOrDefaultAsync(m => m.DocumentId == id);
            if (uploadedDocument == null)
            {
                return NotFound();
            }

            return View(uploadedDocument);
        }

        // GET: UploadedDocuments/Create
        public IActionResult Create()
        {

            ViewBag.ApplicationId = TempData["applicationid"];
            TempData.Keep();
            return View();
        }

        // POST: UploadedDocuments/Create

        [HttpPost]
        public async Task<IActionResult> Create([Bind("DocumentId,PanCard,AadharCard,SalarySlip,Loa,Noc,Agreement,DocumentverifiedStatus,ApplicationId,LoanApprovalStatus")] UploadedDocument uploadedDocument,
            IFormFile PanUpload,IFormFile AadharUpload, IFormFile SalaryUpload,IFormFile LoaUpload,IFormFile NocUpload, IFormFile AgreementUpload)
        {
            var pa = Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Upload"));
            
            //Pan Card Upload
            string panfile = TempData["applicationid"]+"PAN" + Path.GetExtension(PanUpload.FileName);
            uploadedDocument.PanCard = "~/Upload/" + panfile;
            panfile = Path.Combine(pa, panfile);
            using (var stream = new FileStream(panfile, FileMode.Create))
            {
                await PanUpload.CopyToAsync(stream);
            }

            //Aadhar Upload
            string aadharfile = TempData["applicationid"] + "Aadhar" + Path.GetExtension(AadharUpload.FileName);
            uploadedDocument.AadharCard = "~/Upload/" + aadharfile;
            aadharfile = Path.Combine(pa, aadharfile);
            using (var stream = new FileStream(aadharfile, FileMode.Create))
            {
                await AadharUpload.CopyToAsync(stream);
            }
            //Salary Upload
            string salaryfile = TempData["applicationid"] + "Salary" + Path.GetExtension(SalaryUpload.FileName);
            uploadedDocument.SalarySlip = "~/Upload/" + salaryfile;
            salaryfile = Path.Combine(pa, salaryfile);
            using (var stream = new FileStream(salaryfile, FileMode.Create))
            {
                await SalaryUpload.CopyToAsync(stream);
            }

            //Loa Upload
            string loafile = TempData["applicationid"] + "Loa" + Path.GetExtension(LoaUpload.FileName);
            uploadedDocument.Loa = "~/Upload/" + loafile;
            loafile = Path.Combine(pa, loafile);
            using (var stream = new FileStream(loafile, FileMode.Create))
            {
                await LoaUpload.CopyToAsync(stream);
            }

            //Noc Upload
            string nocfile = TempData["applicationid"] + "Noc" + Path.GetExtension(NocUpload.FileName);
            uploadedDocument.Noc = "~/Upload/" + nocfile;
            nocfile = Path.Combine(pa, nocfile);
            using (var stream = new FileStream(nocfile, FileMode.Create))
            {
                await NocUpload.CopyToAsync(stream);
            }

            //Agreement upload
            string agreementfile = TempData["applicationid"] + "Agreement" + Path.GetExtension(AgreementUpload.FileName);
            uploadedDocument.Agreement = "~/Upload/" + agreementfile;
            agreementfile = Path.Combine(pa, agreementfile);
            using (var stream = new FileStream(agreementfile, FileMode.Create))
            {
                await AgreementUpload.CopyToAsync(stream);
            }

            var uid = (from d in _context.UploadedDocuments orderby d.DocumentId descending select d.DocumentId).FirstOrDefault();

            if (uid == 0)
            {
                TempData["Docid"] = 9000;
                ViewBag.DocumnetID = TempData.Peek("Docid");
            }
            else
            {
                TempData["Docid"] = ++uid;
                ViewBag.DocumnetID = TempData.Peek("Docid");
            }
            ViewBag.ApplicationID = TempData["applicationid"];
            uploadedDocument.DocumentId = ViewBag.DocumnetID;
            uploadedDocument.ApplicationId = ViewBag.ApplicationID;
            uploadedDocument.DocumentverifiedStatus = "Sent for Verification";
            uploadedDocument.LoanApprovalStatus = "Sent for Approval";
            _context.Add(uploadedDocument);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }
    }
}

        

        

EfcoreLayout/Views/UploadedDocuments/Create.cshtml
@model EfcoreLayout.Models.UploadedDocument

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/CutomerLayout.cshtml";
}

<h1>Upload Document</h1>

<hr />
<div class="container">
    @*@using  (Html.BeginForm("FileUpload","UploadedDocuments",FormMethod.Post,new { enctype="multipart/form-data"}))*@
    <form method="post" enctype="multipart/form-data" asp-controller="UploadedDocuments" asp-action="Create">
        <div class="form-horizontal">
            
            
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.PanCard, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @*@Html.EditorFor(model => model.Photo, new { htmlAttributes = new { @class = "form-control" } })*@
                    <input type="file" name="PanUpload" required />
                    @Html.ValidationMessageFor(model => model.PanCard, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.AadharCard, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @*@Html.EditorFor(model => model.Photo, new { htmlAttributes = new { @class = "form-control" } })*@
                    <input type="file" name="AadharUpload" required />
                    @Html.ValidationMessageFor(model => model.AadharCard, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.SalarySlip, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @*@Html.EditorFor(model => model.Photo, new { htmlAttributes = new { @class = "form-control" } })*@
                    <input type="file" name="SalaryUpload" required />
                    @Html.ValidationMessageFor(model => model.SalarySlip, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Loa, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @*@Html.EditorFor(model => model.Photo, new { htmlAttributes = new { @class = "form-control" } })*@
                    <input type="file" name="LoaUpload" required />
                    @Html.ValidationMessageFor(model => model.Loa, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Noc, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @*@Html.EditorFor(model => model.Photo, new { htmlAttributes = new { @class = "form-control" } })*@
                    <input type="file" name="NocUpload" required />
                    @Html.ValidationMessageFor(model => model.Noc, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Agreement, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @*@Html.EditorFor(model => model.Photo, new { htmlAttributes = new { @class = "form-control" } })*@
                    <input type="file" name="AgreementUpload" required />
                    @Html.ValidationMessageFor(model => model.Agreement, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Upload Documents" class="btn btn-secondary" />
                </div>
            </div>
        </div>

    </form>
    </div>

EfcoreLayout/Views/UploadedDocuments/Delete.cshtml
@model EfcoreLayout.Models.UploadedDocument

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/CutomerLayout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UploadedDocument</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PanCard)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PanCard)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AadharCard)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AadharCard)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SalarySlip)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SalarySlip)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Loa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Loa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Noc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Noc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Agreement)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Agreement)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DocumentverifiedStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DocumentverifiedStatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Application)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Application.ApplicationId)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="DocumentId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

EfcoreLayout/Views/UploadedDocuments/Details.cshtml
@model EfcoreLayout.Models.UploadedDocument

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/CutomerLayout.cshtml";
}

<h1>Uploaded Documents</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DocumentverifiedStatus)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DocumentverifiedStatus)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LoanApprovalStatus)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LoanApprovalStatus)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Application)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Application.ApplicationId)
        </dd>
    </dl>
</div>
<br />  
<p style="color:Red">
    *Please Check the Details You Have Filled before Submitting
</p>

<div>
    <a asp-controller="home" asp-action="index" class="btn btn-success">SUBMIT</a>

</div>

EfcoreLayout/Views/UploadedDocuments/Index.cshtml
@model IEnumerable<EfcoreLayout.Models.UploadedDocument>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/CutomerLayout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DocumentverifiedStatus)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LoanApprovalStatus)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Application)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DocumentverifiedStatus)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LoanApprovalStatus)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Application.ApplicationId)
            </td>

        </tr>
        }
    </tbody>
</table>

<a asp-controller="home" asp-action="index" class="btn btn-success">SUBMIT</a>