EfcoreLayout/Controllers/UserLoginController.cs
using EfcoreLayout.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EfcoreLayout.Controllers
{
    public class UserLoginController : Controller
    {
        private readonly HomeLoanContext db;
        public UserLoginController(HomeLoanContext context)
        {
            db = context;
        }
        public IActionResult Index()
        {
            return View();
        }
         
        public IActionResult CustomerPage(UserDetail user)
        {
            var mail = user.Email;
            var id = (from y in db.UserDetails
                     where y.Email.Equals(mail)
                     select y.ApplicationId).FirstOrDefault();
            var userinfo = db.UserDetails.Find(id);
            var docid = (from w in db.UploadedDocuments
                         where w.ApplicationId.Equals(id)
                         select w.DocumentId).FirstOrDefault();

            var doc = db.UploadedDocuments.Find(docid);
            if (doc.LoanApprovalStatus == "Loan Approved" )
            {
                var amount = (from w in db.LoanDetails
                              where w.ApplicationId.Equals(id)
                              select w.Amount).FirstOrDefault();
                ViewBag.Balance = amount;
            }
            else
            {
                ViewBag.Balance = 0;
            }


            TempData["userid"] = id;
            TempData.Keep();
            return View(userinfo);
        }

        public IActionResult Profile()
        {
            var id = TempData["userid"];
            var userinfo = db.UserDetails.Find(id);
            return View(userinfo);

        }

        public IActionResult LoanTracker()
        {
            
            return View();
        }

        [HttpPost]

        public IActionResult LoanTracker(LoanStatus loanStatus)
        {
            var checkid = (from c in db.UploadedDocuments
                           where c.ApplicationId.Equals(loanStatus.ApplicationId)
                           select c.ApplicationId).FirstOrDefault();
            if(checkid!=null)
            {
                var statusid = (from x in db.LoanStatuses orderby x.StatusId descending select x.StatusId).FirstOrDefault();
                if (statusid == 0)
                {
                    loanStatus.StatusId = 10000;
                }
                else
                {
                    loanStatus.StatusId = ++statusid;   
                }

                var docid = (from w in db.UploadedDocuments
                             where w.ApplicationId.Equals(checkid)
                             select w.DocumentId).FirstOrDefault();

                var doc = db.UploadedDocuments.Find(docid);

                if (doc.DocumentverifiedStatus == "Sent for Verification")
                {
                    loanStatus.TrackStatus = "Sent for Verification";
                }
                else if (doc.DocumentverifiedStatus == "Documnet Verification Failed")
                {
                    loanStatus.TrackStatus = doc.DocumentverifiedStatus;
                }

                else if (doc.DocumentverifiedStatus == "Document Verified" && doc.LoanApprovalStatus == "Sent for Approval")
                {
                    loanStatus.TrackStatus = "Verified and Sent for Final Approval";
                }
                else if (doc.LoanApprovalStatus == "Loan Approved" || doc.LoanApprovalStatus == "Loan Rejected")
                {
                    loanStatus.TrackStatus = doc.LoanApprovalStatus;
                }

                ViewBag.Tracker = loanStatus.TrackStatus;
                db.SaveChanges();
                return View();

            }   
                
            return View();
        }


        public IActionResult CheckBalance()
        {

            return View();
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userDetail = db.UserDetails
                .FirstOrDefault(m => m.ApplicationId == id);
            if (userDetail == null)
            {
                return NotFound();
            }

            return View(userDetail);
        }
        
        public IActionResult Login()
        {
            return View();
            
        }

        [HttpPost]
        public IActionResult Login(UserDetail user)
        {
            string email = user.Email;
            string Password = user.UserPassword;

            var emailcheck = (from c in db.UserDetails where c.Email.Equals(user.Email) select c.Email).FirstOrDefault();
            var passwordcheck= (from d in db.UserDetails where d.UserPassword.Equals(user.UserPassword) select d.UserPassword).FirstOrDefault();

            if (emailcheck != null && passwordcheck!=null)
            {
                return RedirectToAction("CustomerPage","userlogin",user);
            }
            else
            {
                ViewBag.Error="Invalid Email ID or Password";
                return View();
            }
        }
    }
}

EfcoreLayout/Views/UserLogin/CheckBalance.cshtml
@{
    ViewData["Title"] = "CheckBalance";
    Layout = "~/Views/UserLogin/WelcomeLayout.cshtml";
}

<h1>Balance</h1>

EfcoreLayout/Views/UserLogin/CustomerPage.cshtml
@model EfcoreLayout.Models.UserDetail
@{
    ViewData["Title"] = "CustomerPage";
    Layout = "~/Views/UserLogin/WelcomeLayout.cshtml";

}

<center>

    <h1>Welcome To Customer Dashboard, @Model.FirstName @Model.LastName</h1>

</center>

<br />
<br />
<h3>Account Balance:@ViewBag.Balance</h3>

EfcoreLayout/Views/UserLogin/LoanTracker.cshtml
@model EfcoreLayout.Models.LoanStatus

@{
    ViewData["Title"] = "LoanTracker";
    Layout = "~/Views/UserLogin/WelcomeLayout.cshtml";
}

<center><h1>LoanTracker</h1></center>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="LoanTracker">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ApplicationId" class="control-label"></label>
                <input type="number" asp-for="ApplicationId" class="form-control">
            </div>
            <div class="form-group">
                <label asp-for="TrackStatus" class="control-label"></label>
                <input asp-for="TrackStatus" class="form-control" value="@ViewBag.Tracker" disabled/>
                <span asp-validation-for="TrackStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Track" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

EfcoreLayout/Views/UserLogin/Login.cshtml
@model EfcoreLayout.Models.UserDetail

@{
    ViewData["Title"] = "Login";
    Layout = "~/Views/Shared/BankingMaster.cshtml";
}

<center><h1>User Login</h1></center>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>


            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" autocomplete="off"/>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserPassword" class="control-label"></label>
                <input type="password" asp-for="UserPassword" class="form-control" />
                <span asp-validation-for="UserPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Login" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div style="color:red">
    @ViewBag.Error <br />
</div>

<div>
    <a asp-controller="userdetails" asp-action="Create">New User ? Apply for a Loan Now</a>
</div>

EfcoreLayout/Views/UserLogin/Profile.cshtml
@model EfcoreLayout.Models.UserDetail
@{
    ViewData["Title"] = "CustomerPage";
    Layout = "~/Views/UserLogin/WelcomeLayout.cshtml";

}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>

    <div>
        <h3> PROFILE</h3>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.ApplicationId)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.ApplicationId)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.FirstName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.FirstName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.MiddleName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.MiddleName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.LastName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.LastName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Email)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Email)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PhoneNumber)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.DateOfBirth)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.DateOfBirth)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Gender)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Gender)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Nationality)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Nationality)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.AadharNumber)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.AadharNumber)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.PanNumber)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PanNumber)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.BankAccountNumber)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.BankAccountNumber)
            </dd>
        </dl>
    </div>
    
</body>
</html>

EfcoreLayout/Views/UserLogin/WelcomeLayout.cshtml
@model EfcoreLayout.Models.UserDetail

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        body {
            font-family: 'Trebuchet MS';
        }

        .sidenav {
            height: 100%;
            width: 190px;
            position: fixed;
            z-index: 1;
            top: 0;
            left: 0;
            background-color: #111;
            overflow-x: hidden;
            padding-top: 20px;
        }

            .sidenav a {
                padding: 6px 8px 6px 16px;
                text-decoration: none;
                font-size: 25px;
                color:aqua;
                display: block;
            }

                .sidenav a:hover {
                    background-color:deepskyblue;
                    color: #f1f1f1;
                }

        .navbar-brand {
            padding: 6px 8px 6px 16px;
            text-decoration: none;
            font-size: 25px;
            color: #818181;
            display: block;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-danger border-bottom box-shadow mb-3">
            <div class="container">

                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HOME LOAN</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

            </div>
        </nav>
    </header>


    <div class="sidenav">

        <a asp-controller="UserLogin" asp-action="Profile" asp-route-id="@TempData["userid"]">PROFILE</a>
        <a asp-controller="UserLogin" asp-action="LoanTracker">LOAN TRACKER</a>
        <a asp-controller="UserLogin" asp-action="Login">LOGOUT</a>
    </div>



    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - HomeLoan - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>